version: 2.1

common: &common
  working_directory: '~/bouncycastle-maven-plugin'
  docker:
    - image: 'circleci/openjdk:8'

jobs:
  vendor:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
            - bouncycastle-maven-plugin-{{ .Branch }}-{{ .Revision }}
            - bouncycastle-maven-plugin-{{ .Branch }}
            - bouncycastle-maven-plugin
      - run: mvn dependency:go-offline
      - save_cache:
          key: bouncycastle-maven-plugin-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.m2
  test:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
            - bouncycastle-maven-plugin-{{ .Branch }}-{{ .Revision }}
            - bouncycastle-maven-plugin-{{ .Branch }}
            - bouncycastle-maven-plugin
      - run: mvn verify

  publish:
    <<: *common
    steps:
      - checkout
      - restore_cache:
          keys:
            - bouncycastle-maven-plugin-{{ .Branch }}-{{ .Revision }}
            - bouncycastle-maven-plugin-{{ .Branch }}
            - bouncycastle-maven-plugin
      - run: PGP_RINGS="$(echo ${PGP_RINGS_ENCODED} | base64 --decode)" mvn deploy -P deploy -s settings.xml

workflows:
  full:
    jobs:
      - vendor
      - test:
          requires:
            - vendor
      - publish:
          requires:
            - vendor
            - test
          filters:
            branches:
              only: master
